const dummyData = [
  {
    login: "ctcoleman",
    id: 65408486,
    node_id: "MDQ6VXNlcjY1NDA4NDg2",
    avatar_url: "https://avatars3.githubusercontent.com/u/65408486?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ctcoleman",
    html_url: "https://github.com/ctcoleman",
    followers_url: "https://api.github.com/users/ctcoleman/followers",
    following_url:
      "https://api.github.com/users/ctcoleman/following{/other_user}",
    gists_url: "https://api.github.com/users/ctcoleman/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ctcoleman/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ctcoleman/subscriptions",
    organizations_url: "https://api.github.com/users/ctcoleman/orgs",
    repos_url: "https://api.github.com/users/ctcoleman/repos",
    events_url: "https://api.github.com/users/ctcoleman/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ctcoleman/received_events",
    type: "User",
    site_admin: false,
    name: "Chris",
    company: "Lambda Student",
    blog: "https://www.facebook.com/ctcoleman510/",
    location: "New York, USA",
    email: null,
    hireable: true,
    bio: "<!--Student--WebDev--Lambda--Nerd-->\r\n",
    twitter_username: "RefuseRemain",
    public_repos: 35,
    public_gists: 1,
    followers: 1,
    following: 1,
    created_at: "2020-05-15T14:43:40Z",
    updated_at: "2020-08-13T23:24:21Z"
  },
  {
    login: "ntilbe",
    id: 61669896,
    node_id: "MDQ6VXNlcjYxNjY5ODk2",
    avatar_url: "https://avatars1.githubusercontent.com/u/61669896?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ntilbe",
    html_url: "https://github.com/ntilbe",
    followers_url: "https://api.github.com/users/ntilbe/followers",
    following_url: "https://api.github.com/users/ntilbe/following{/other_user}",
    gists_url: "https://api.github.com/users/ntilbe/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ntilbe/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ntilbe/subscriptions",
    organizations_url: "https://api.github.com/users/ntilbe/orgs",
    repos_url: "https://api.github.com/users/ntilbe/repos",
    events_url: "https://api.github.com/users/ntilbe/events{/privacy}",
    received_events_url: "https://api.github.com/users/ntilbe/received_events",
    type: "User",
    site_admin: false,
    name: "Nicole Tilbe",
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: true,
    bio: null,
    twitter_username: null,
    public_repos: 60,
    public_gists: 1,
    followers: 19,
    following: 24,
    created_at: "2020-03-02T00:07:20Z",
    updated_at: "2020-08-14T15:02:23Z"
  },
  {
    login: "JJAleman",
    id: 40443899,
    node_id: "MDQ6VXNlcjQwNDQzODk5",
    avatar_url: "https://avatars0.githubusercontent.com/u/40443899?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/JJAleman",
    html_url: "https://github.com/JJAleman",
    followers_url: "https://api.github.com/users/JJAleman/followers",
    following_url:
      "https://api.github.com/users/JJAleman/following{/other_user}",
    gists_url: "https://api.github.com/users/JJAleman/gists{/gist_id}",
    starred_url: "https://api.github.com/users/JJAleman/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/JJAleman/subscriptions",
    organizations_url: "https://api.github.com/users/JJAleman/orgs",
    repos_url: "https://api.github.com/users/JJAleman/repos",
    events_url: "https://api.github.com/users/JJAleman/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/JJAleman/received_events",
    type: "User",
    site_admin: false,
    name: "Juan Aleman",
    company: null,
    blog: "",
    location: "Pharr, TX",
    email: null,
    hireable: true,
    bio: null,
    twitter_username: null,
    public_repos: 95,
    public_gists: 0,
    followers: 5,
    following: 3,
    created_at: "2018-06-20T22:53:12Z",
    updated_at: "2020-08-06T02:53:33Z"
  }
];

export default dummyData;
